trigger: none
pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: CIConfig 

steps:
- task: Docker@2
  displayName: 'Login to ACR $(acrLoginServer)'
  inputs:
    command: login
    containerRegistry: '$(acrServiceConnection)'

- script: |
    docker run --rm \
      -v $(System.DefaultWorkingDirectory):/app \
      -w /app \
      $(acrImageName) \
      ruff check app tests
  displayName: 'Run Ruff Linter (in container)'
  failOnStderr: true

- script: |
    docker run --rm \
      -v $(System.DefaultWorkingDirectory):/app \
      -w /app \
      $(acrImageName) \
      ruff format --check app tests
  displayName: 'Check Ruff Formatting (in container)'
  failOnStderr: true

- script: |
    mkdir -p $(testResultsDirOnAgent)
  displayName: 'Create test results directory on agent'

- script: |
    docker run --rm \
      -v $(System.DefaultWorkingDirectory):/app \
      -v $(testResultsDirOnAgent):$(testResultsDirInContainer) \
      -w /app \
      $(acrImageName) \
      pytest \
        --cov=app \
        --cov-report=term \
        --cov-report=xml:$(testResultsDirInContainer)/coverage.xml \
        --junitxml=$(testResultsDirInContainer)/TEST-results.xml \
        --cov-fail-under=80 \
        tests/
  displayName: 'Run Pytest with Coverage (in container, Fail < 80%)'
  failOnStderr: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(testResultsDirOnAgent)/TEST-results.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'

- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(testResultsDirOnAgent)/coverage.xml'
  displayName: 'Publish Code Coverage Results'

- task: Docker@2
  displayName: Logout from ACR
  condition: always()
  inputs:
    command: logout
    containerRegistry: '$(acrServiceConnection)'
